package dev.terraforge.plugin;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Properties;

/**
 * Which source revision this jar was built from, plus the identity of the jar actually running.
 *
 * <p>Exists because a plugin jar built from an uncommitted working tree is byte-wise
 * indistinguishable from a released one unless the build records the commit into it. Without that
 * record, terrain generated by a server cannot be traced back to reviewed source, and a bug report
 * cannot be reproduced from any commit. The build writes {@code /terraforge-build.properties} via
 * resource filtering; this class reads it back.
 *
 * <p>Deliberately no build timestamp: the root build script pins archives to reproducible output
 * ({@code isPreserveFileTimestamps = false}), and a timestamp would make every rebuild differ.
 *
 * <p>Every operation degrades to a readable placeholder instead of throwing. Provenance is
 * diagnostic metadata, so a missing resource (a third party embedding the classes without the
 * generated file) or an unreadable jar must never keep the plugin from enabling.
 */
public record BuildProvenance(String version, String commit, String dirtyState) {

    /** Written by {@code processResources} in {@code terraforge-plugin/build.gradle.kts}. */
    static final String RESOURCE = "/terraforge-build.properties";

    /** Value used for anything the build could not determine (no git, or a source-tarball build). */
    static final String UNKNOWN = "unknown";

    /** Returned by {@link #sha256(File)} when the jar cannot be read. */
    static final String UNAVAILABLE = "unavailable";

    private static final int SHORT_COMMIT_LENGTH = 7;
    private static final int DIGEST_BUFFER_BYTES = 64 * 1024;

    /** Reads the generated resource off the classpath; never fails. */
    public static BuildProvenance load() {
        try (InputStream stream = BuildProvenance.class.getResourceAsStream(RESOURCE)) {
            return from(stream);
        } catch (IOException exception) {
            return unknown();
        }
    }

    /** Package-private seam for tests: a {@code null} stream models the resource being absent. */
    static BuildProvenance from(InputStream stream) {
        if (stream == null) {
            return unknown();
        }
        Properties properties = new Properties();
        try {
            properties.load(stream);
        } catch (IOException | IllegalArgumentException exception) {
            // A truncated or malformed resource says nothing trustworthy about the build.
            return unknown();
        }
        return new BuildProvenance(read(properties, "version"), read(properties, "commit"),
                read(properties, "dirty"));
    }

    static BuildProvenance unknown() {
        return new BuildProvenance(UNKNOWN, UNKNOWN, UNKNOWN);
    }

    /**
     * SHA-256 of a jar as lowercase hex, or {@value #UNAVAILABLE}. Streamed in fixed-size chunks
     * because the shaded plugin jar is roughly 10 MB and buffering it whole would waste that much
     * heap on a diagnostic line.
     */
    public static String sha256(File file) {
        if (file == null) {
            return UNAVAILABLE;
        }
        try (InputStream stream = new FileInputStream(file)) {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] buffer = new byte[DIGEST_BUFFER_BYTES];
            for (int read = stream.read(buffer); read >= 0; read = stream.read(buffer)) {
                digest.update(buffer, 0, read);
            }
            return HexFormat.of().formatHex(digest.digest());
        } catch (IOException | NoSuchAlgorithmException exception) {
            return UNAVAILABLE;
        }
    }

    /** True only when the build script positively observed uncommitted changes. */
    public boolean dirty() {
        return "true".equals(dirtyState);
    }

    /** True when this jar names the exact revision it was built from. */
    public boolean commitKnown() {
        return !UNKNOWN.equals(commit) && !commit.isBlank();
    }

    /** One banner-sized line, e.g. {@code 0.1.2 commit 39984e0 (clean)}. */
    public String describe() {
        if (!commitKnown()) {
            return version + " commit unknown (no git metadata at build time)";
        }
        return version + " commit " + shortCommit() + " (" + treeState() + ")";
    }

    private String shortCommit() {
        return commit.length() > SHORT_COMMIT_LENGTH ? commit.substring(0, SHORT_COMMIT_LENGTH) : commit;
    }

    private String treeState() {
        if (dirty()) {
            return "DIRTY";
        }
        // Neither "true" nor "false": the build could not run `git status`, so claiming "clean"
        // would be a guess -- exactly the guess that let an uncommitted jar ship unnoticed.
        return "false".equals(dirtyState) ? "clean" : "working tree state unknown";
    }

    private static String read(Properties properties, String key) {
        String value = properties.getProperty(key, "").trim();
        return value.isEmpty() ? UNKNOWN : value;
    }
}
